version: '3'
services:
  go:
    build:
      context: .
      dockerfile: DockerFile.backend
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    image: gcr.io/freee-intern-317806/backend:v3
    volumes:
      - .:/app
    ports:
      - 1323:1323
    depends_on:
      - "db"

  db:
    build:
      context: .
      dockerfile: DockerFile.db
    image: gcr.io/freee-intern-317806/db:v2
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: godb
      MYSQL_USER: go
      MYSQL_PASSWORD: pass
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

volumes:
  db-data:
    driver: local